// <auto-generated />
using System;
using FirebirdSql.EntityFrameworkCore.Firebird.Metadata;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models.DBRealization;

namespace Models.DBRealization.Migrations.DataModel
{
    [DbContext(typeof(DBModel))]
    [Migration("20211221110132_DataModel_13")]
    partial class DataModel_13
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 31)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("Fb:ValueGenerationStrategy", FbValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Models.Collections.DBObservable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("DBObservable_DbSet");
                });

            modelBuilder.Entity("Models.Collections.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comments_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("ContractIssueDate2_28_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("ContractNumber_28_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<short>("CorrectionNumber_DB")
                        .HasColumnType("SMALLINT");

                    b.Property<string>("EndPeriod_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("ExecEmail_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("ExecPhone_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("ExportDate_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("FIOexecutor_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("FormNum_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("GradeExecutor_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<bool>("IsCorrection_DB")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("NumberInOrder_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("OrganisationReciever_28_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("PermissionDocumentName1_28_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("PermissionDocumentName27_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("PermissionDocumentName_28_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("PermissionIssueDate1_28_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("PermissionIssueDate27_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("PermissionIssueDate_28_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("PermissionNumber1_28_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("PermissionNumber27_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("PermissionNumber_28_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int?>("ReportsId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SourcesQuantity26_DB")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StartPeriod_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("ValidBegin1_28_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("ValidBegin27_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("ValidBegin2_28_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("ValidBegin_28_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("ValidThru1_28_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("ValidThru27_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("ValidThru2_28_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("ValidThru_28_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int?>("Year_DB")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ReportsId");

                    b.ToTable("ReportCollection_DbSet");
                });

            modelBuilder.Entity("Models.Collections.Reports", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DBObservableId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Master_DBId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DBObservableId");

                    b.HasIndex("Master_DBId");

                    b.ToTable("ReportsCollection_DbSet");
                });

            modelBuilder.Entity("Models.Form10", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("Fax_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("FormNum_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("GradeFIO_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("Inn_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("JurLicoAddress_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("JurLicoFactAddress_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("JurLico_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("Kpp_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int>("NumberInOrder_DB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfFields_DB")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Okfs_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("Okogu_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("Okopf_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("Okpo_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("Oktmo_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("Okved_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("OrganUprav_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("RegNo_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int?>("ReportId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShortJurLico_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("SubjectRF_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("Telephone_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.ToTable("form_10");
                });

            modelBuilder.Entity("Models.Form11", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Activity_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<short?>("Category_DB")
                        .HasColumnType("SMALLINT");

                    b.Property<string>("CreationDate_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("CreatorOKPO_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("DocumentDate_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<bool>("DocumentDate_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("DocumentNumber_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<bool>("DocumentNumber_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.Property<short?>("DocumentVid_DB")
                        .HasColumnType("SMALLINT");

                    b.Property<bool>("DocumentVid_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("FactoryNumber_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("FormNum_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int>("NumberInOrder_DB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfFields_DB")
                        .HasColumnType("INTEGER");

                    b.Property<short?>("OperationCode_DB")
                        .HasColumnType("SMALLINT");

                    b.Property<bool>("OperationCode_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("OperationDate_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<bool>("OperationDate_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("Owner_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("PackName_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("PackNumber_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("PackType_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("PassportNumber_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<short?>("PropertyCode_DB")
                        .HasColumnType("SMALLINT");

                    b.Property<string>("ProviderOrRecieverOKPO_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int?>("Quantity_DB")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Radionuclids_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int?>("ReportId")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("SignedServicePeriod_DB")
                        .HasColumnType("FLOAT");

                    b.Property<string>("TransporterOKPO_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("Type_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.ToTable("form_11");
                });

            modelBuilder.Entity("Models.Form12", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreationDate_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("CreatorOKPO_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("DocumentDate_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<bool>("DocumentDate_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("DocumentNumber_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<bool>("DocumentNumber_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.Property<short?>("DocumentVid_DB")
                        .HasColumnType("SMALLINT");

                    b.Property<bool>("DocumentVid_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("FactoryNumber_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("FormNum_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("Mass_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("NameIOU_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int>("NumberInOrder_DB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfFields_DB")
                        .HasColumnType("INTEGER");

                    b.Property<short?>("OperationCode_DB")
                        .HasColumnType("SMALLINT");

                    b.Property<bool>("OperationCode_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("OperationDate_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<bool>("OperationDate_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("Owner_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("PackName_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("PackNumber_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("PackType_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("PassportNumber_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<short?>("PropertyCode_DB")
                        .HasColumnType("SMALLINT");

                    b.Property<string>("ProviderOrRecieverOKPO_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int?>("ReportId")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("SignedServicePeriod_DB")
                        .HasColumnType("FLOAT");

                    b.Property<string>("TransporterOKPO_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.ToTable("form_12");
                });

            modelBuilder.Entity("Models.Form13", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Activity_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<short?>("AggregateState_DB")
                        .HasColumnType("SMALLINT");

                    b.Property<string>("CreationDate_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("CreatorOKPO_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("DocumentDate_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<bool>("DocumentDate_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("DocumentNumber_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<bool>("DocumentNumber_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.Property<short?>("DocumentVid_DB")
                        .HasColumnType("SMALLINT");

                    b.Property<bool>("DocumentVid_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("FactoryNumber_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("FormNum_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int>("NumberInOrder_DB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfFields_DB")
                        .HasColumnType("INTEGER");

                    b.Property<short?>("OperationCode_DB")
                        .HasColumnType("SMALLINT");

                    b.Property<bool>("OperationCode_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("OperationDate_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<bool>("OperationDate_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("Owner_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("PackName_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("PackNumber_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("PackType_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("PassportNumber_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<short?>("PropertyCode_DB")
                        .HasColumnType("SMALLINT");

                    b.Property<string>("ProviderOrRecieverOKPO_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("Radionuclids_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int?>("ReportId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TransporterOKPO_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("Type_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.ToTable("form_13");
                });

            modelBuilder.Entity("Models.Form14", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActivityMeasurementDate_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("Activity_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<short?>("AggregateState_DB")
                        .HasColumnType("SMALLINT");

                    b.Property<string>("DocumentDate_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<bool>("DocumentDate_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("DocumentNumber_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<bool>("DocumentNumber_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.Property<short?>("DocumentVid_DB")
                        .HasColumnType("SMALLINT");

                    b.Property<bool>("DocumentVid_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("FormNum_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("Mass_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("Name_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int>("NumberInOrder_DB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfFields_DB")
                        .HasColumnType("INTEGER");

                    b.Property<short?>("OperationCode_DB")
                        .HasColumnType("SMALLINT");

                    b.Property<bool>("OperationCode_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("OperationDate_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<bool>("OperationDate_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("Owner_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("PackName_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("PackNumber_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("PackType_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("PassportNumber_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<short?>("PropertyCode_DB")
                        .HasColumnType("SMALLINT");

                    b.Property<string>("ProviderOrRecieverOKPO_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("Radionuclids_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int?>("ReportId")
                        .HasColumnType("INTEGER");

                    b.Property<short?>("Sort_DB")
                        .HasColumnType("SMALLINT");

                    b.Property<string>("TransporterOKPO_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("Volume_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.ToTable("form_14");
                });

            modelBuilder.Entity("Models.Form15", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Activity_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("CreationDate_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("DocumentDate_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<bool>("DocumentDate_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("DocumentNumber_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<bool>("DocumentNumber_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.Property<short?>("DocumentVid_DB")
                        .HasColumnType("SMALLINT");

                    b.Property<bool>("DocumentVid_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("FactoryNumber_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("FcpNumber_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("FormNum_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int>("NumberInOrder_DB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfFields_DB")
                        .HasColumnType("INTEGER");

                    b.Property<short?>("OperationCode_DB")
                        .HasColumnType("SMALLINT");

                    b.Property<bool>("OperationCode_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("OperationDate_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<bool>("OperationDate_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("PackName_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("PackNumber_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("PackType_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("PassportNumber_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("ProviderOrRecieverOKPO_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int?>("Quantity_DB")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Radionuclids_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("RefineOrSortRAOCode_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int?>("ReportId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StatusRAO_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("StoragePlaceCode_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("StoragePlaceName_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("Subsidy_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("TransporterOKPO_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("Type_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.ToTable("form_15");
                });

            modelBuilder.Entity("Models.Form16", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActivityMeasurementDate_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("AlphaActivity_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("BetaGammaActivity_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("CodeRAO_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("DocumentDate_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<bool>("DocumentDate_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("DocumentNumber_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<bool>("DocumentNumber_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.Property<short?>("DocumentVid_DB")
                        .HasColumnType("SMALLINT");

                    b.Property<bool>("DocumentVid_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("FcpNumber_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("FormNum_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("MainRadionuclids_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("Mass_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int>("NumberInOrder_DB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfFields_DB")
                        .HasColumnType("INTEGER");

                    b.Property<short?>("OperationCode_DB")
                        .HasColumnType("SMALLINT");

                    b.Property<bool>("OperationCode_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("OperationDate_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<bool>("OperationDate_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("PackName_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("PackNumber_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("PackType_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("ProviderOrRecieverOKPO_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("QuantityOZIII_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("RefineOrSortRAOCode_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int?>("ReportId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StatusRAO_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("StoragePlaceCode_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("StoragePlaceName_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("Subsidy_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("TransporterOKPO_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("TransuraniumActivity_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("TritiumActivity_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("Volume_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.ToTable("form_16");
                });

            modelBuilder.Entity("Models.Form17", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AlphaActivity_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("BetaGammaActivity_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("CodeRAO_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("DocumentDate_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<bool>("DocumentDate_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("DocumentNumber_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<bool>("DocumentNumber_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.Property<short?>("DocumentVid_DB")
                        .HasColumnType("SMALLINT");

                    b.Property<bool>("DocumentVid_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("FcpNumber_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("FormNum_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("FormingDate_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<bool>("FormingDate_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("MassOutOfPack_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("Mass_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<bool>("Mass_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.Property<int>("NumberInOrder_DB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfFields_DB")
                        .HasColumnType("INTEGER");

                    b.Property<short?>("OperationCode_DB")
                        .HasColumnType("SMALLINT");

                    b.Property<bool>("OperationCode_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("OperationDate_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<bool>("OperationDate_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("PackFactoryNumber_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<bool>("PackFactoryNumber_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("PackName_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<bool>("PackName_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("PackNumber_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<bool>("PackNumber_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("PackType_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<bool>("PackType_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("PassportNumber_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<bool>("PassportNumber_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("ProviderOrRecieverOKPO_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<bool>("ProviderOrRecieverOKPO_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("Quantity_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("Radionuclids_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("RefineOrSortRAOCode_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int?>("ReportId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SpecificActivity_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("StatusRAO_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("StoragePlaceCode_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<bool>("StoragePlaceCode_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("StoragePlaceName_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<bool>("StoragePlaceName_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("Subsidy_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<bool>("Sum_DB")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("TransporterOKPO_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<bool>("TransporterOKPO_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("TransuraniumActivity_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("TritiumActivity_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("VolumeOutOfPack_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("Volume_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<bool>("Volume_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.ToTable("form_17");
                });

            modelBuilder.Entity("Models.Form18", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AlphaActivity_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("BetaGammaActivity_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("CodeRAO_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("DocumentDate_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<bool>("DocumentDate_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("DocumentNumber_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<bool>("DocumentNumber_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.Property<short?>("DocumentVid_DB")
                        .HasColumnType("SMALLINT");

                    b.Property<bool>("DocumentVid_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("FcpNumber_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("FormNum_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("IndividualNumberZHRO_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<bool>("IndividualNumberZHRO_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("Mass21_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("Mass7_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<bool>("Mass7_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.Property<int>("NumberInOrder_DB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfFields_DB")
                        .HasColumnType("INTEGER");

                    b.Property<short?>("OperationCode_DB")
                        .HasColumnType("SMALLINT");

                    b.Property<bool>("OperationCode_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("OperationDate_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<bool>("OperationDate_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("PassportNumber_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<bool>("PassportNumber_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("ProviderOrRecieverOKPO_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<bool>("ProviderOrRecieverOKPO_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("Radionuclids_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("RefineOrSortRAOCode_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int?>("ReportId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SaltConcentration_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<bool>("SaltConcentration_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("SpecificActivity_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("StatusRAO_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("StoragePlaceCode_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<bool>("StoragePlaceCode_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("StoragePlaceName_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<bool>("StoragePlaceName_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("Subsidy_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<bool>("Sum_DB")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("TransporterOKPO_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<bool>("TransporterOKPO_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("TransuraniumActivity_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("TritiumActivity_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("Volume20_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("Volume6_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<bool>("Volume6_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.ToTable("form_18");
                });

            modelBuilder.Entity("Models.Form19", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Activity_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<short?>("CodeTypeAccObject_DB")
                        .HasColumnType("SMALLINT");

                    b.Property<string>("DocumentDate_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<bool>("DocumentDate_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("DocumentNumber_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<bool>("DocumentNumber_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.Property<short?>("DocumentVid_DB")
                        .HasColumnType("SMALLINT");

                    b.Property<bool>("DocumentVid_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("FormNum_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int>("NumberInOrder_DB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfFields_DB")
                        .HasColumnType("INTEGER");

                    b.Property<short?>("OperationCode_DB")
                        .HasColumnType("SMALLINT");

                    b.Property<bool>("OperationCode_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("OperationDate_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<bool>("OperationDate_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("Radionuclids_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int?>("ReportId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.ToTable("form_19");
                });

            modelBuilder.Entity("Models.Form20", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("Fax_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("FormNum_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("GradeFIO_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("Inn_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("JurLicoAddress_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("JurLicoFactAddress_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("JurLico_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("Kpp_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int>("NumberInOrder_DB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfFields_DB")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Okfs_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("Okogu_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("Okopf_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("Okpo_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("Oktmo_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("Okved_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("OrganUprav_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("RegNo_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int?>("ReportId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShortJurLico_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("SubjectRF_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("Telephone_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.ToTable("form_20");
                });

            modelBuilder.Entity("Models.Form21", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AlphaActivityIn_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("AlphaActivityOut_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("BetaGammaActivityIn_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("BetaGammaActivityOut_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("CodeRAOIn_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<bool>("CodeRAOIn_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("CodeRAOout_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<bool>("CodeRAOout_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.Property<short>("CorrectionNumber_DB")
                        .HasColumnType("SMALLINT");

                    b.Property<string>("FormNum_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<short?>("MachineCode_DB")
                        .HasColumnType("SMALLINT");

                    b.Property<bool>("MachineCode_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.Property<bool>("MachineCode_Hidden_Priv2")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("MachinePower_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<bool>("MachinePower_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.Property<bool>("MachinePower_Hidden_Priv2")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("MassIn_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("MassOut_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int>("NumberInOrder_DB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfFields_DB")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NumberOfHoursPerYear_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<bool>("NumberOfHoursPerYear_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.Property<bool>("NumberOfHoursPerYear_Hidden_Priv2")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("NumberOfHoursPerYear_Hidden_P~1");

                    b.Property<string>("QuantityIn_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("QuantityOZIIIout_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("RefineMachineName_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<bool>("RefineMachineName_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.Property<bool>("RefineMachineName_Hidden_Priv2")
                        .HasColumnType("BOOLEAN");

                    b.Property<int?>("ReportId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StatusRAOIn_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<bool>("StatusRAOIn_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("StatusRAOout_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<bool>("StatusRAOout_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.Property<bool>("Sum_DB")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("TransuraniumActivityIn_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("TransuraniumActivityOut_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("TritiumActivityIn_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("TritiumActivityOut_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("VolumeIn_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("VolumeOut_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.ToTable("form_21");
                });

            modelBuilder.Entity("Models.Form210", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvgGammaRaysDosePower_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<short>("CorrectionNumber_DB")
                        .HasColumnType("SMALLINT");

                    b.Property<string>("FcpNumber_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("FormNum_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("IndicatorName_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("InfectedArea_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("MaxGammaRaysDosePower_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int>("NumberInOrder_DB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfFields_DB")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlotCode_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("PlotKadastrNumber_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("PlotName_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int?>("ReportId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WasteDensityAlpha_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("WasteDensityBeta_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.ToTable("form_210");
                });

            modelBuilder.Entity("Models.Form211", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<short>("CorrectionNumber_DB")
                        .HasColumnType("SMALLINT");

                    b.Property<string>("FormNum_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("InfectedArea_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int>("NumberInOrder_DB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfFields_DB")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlotCode_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("PlotKadastrNumber_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("PlotName_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("Radionuclids_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int?>("ReportId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SpecificActivityOfDensePart_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("SpecificActivityOfLiquidPart_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("SpecificActivityOfPlot_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.ToTable("form_211");
                });

            modelBuilder.Entity("Models.Form212", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Activity_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<short>("CorrectionNumber_DB")
                        .HasColumnType("SMALLINT");

                    b.Property<string>("FormNum_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int>("NumberInOrder_DB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfFields_DB")
                        .HasColumnType("INTEGER");

                    b.Property<short?>("ObjectTypeCode_DB")
                        .HasColumnType("SMALLINT");

                    b.Property<short?>("OperationCode_DB")
                        .HasColumnType("SMALLINT");

                    b.Property<string>("ProviderOrRecieverOKPO_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("Radionuclids_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int?>("ReportId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.ToTable("form_212");
                });

            modelBuilder.Entity("Models.Form22", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AlphaActivity_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("BetaGammaActivity_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("CodeRAO_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<bool>("CodeRAO_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.Property<short>("CorrectionNumber_DB")
                        .HasColumnType("SMALLINT");

                    b.Property<string>("FcpNumber_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<bool>("FcpNumber_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("FormNum_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("MainRadionuclids_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<bool>("MainRadionuclids_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("MassInPack_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<bool>("MassInPack_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.Property<bool>("MassInPack_Hidden_Priv2")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("MassOutOfPack_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int>("NumberInOrder_DB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfFields_DB")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PackName_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<bool>("PackName_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.Property<bool>("PackName_Hidden_Priv2")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("PackQuantity_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("PackType_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<bool>("PackType_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.Property<bool>("PackType_Hidden_Priv2")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("QuantityOZIII_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int?>("ReportId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StatusRAO_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<bool>("StatusRAO_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("StoragePlaceCode_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<bool>("StoragePlaceCode_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.Property<bool>("StoragePlaceCode_Hidden_Priv2")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("StoragePlaceName_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<bool>("StoragePlaceName_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.Property<bool>("StoragePlaceName_Hidden_Priv2")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("Subsidy_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<bool>("Subsidy_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.Property<bool>("Sum_DB")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("TransuraniumActivity_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("TritiumActivity_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("VolumeInPack_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<bool>("VolumeInPack_Hidden_Priv")
                        .HasColumnType("BOOLEAN");

                    b.Property<bool>("VolumeInPack_Hidden_Priv2")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("VolumeOutOfPack_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.ToTable("form_22");
                });

            modelBuilder.Entity("Models.Form23", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodeRAO_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<short>("CorrectionNumber_DB")
                        .HasColumnType("SMALLINT");

                    b.Property<string>("DocumentDate_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("DocumentName_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("DocumentNumber_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("ExpirationDate_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("FormNum_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("Mass_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int>("NumberInOrder_DB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfFields_DB")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProjectVolume_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("QuantityOZIII_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int?>("ReportId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StoragePlaceCode_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("StoragePlaceName_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("SummaryActivity_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("Volume_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.ToTable("form_23");
                });

            modelBuilder.Entity("Models.Form24", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodeOYAT_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<short>("CorrectionNumber_DB")
                        .HasColumnType("SMALLINT");

                    b.Property<string>("FcpNumber_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("FormNum_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("MassAnotherReasons_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("MassCreated_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("MassFromAnothersImported_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("MassFromAnothers_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("MassRefined_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("MassRemovedFromAccount_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("MassTransferredToAnother_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int>("NumberInOrder_DB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfFields_DB")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QuantityAnotherReasons_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("QuantityCreated_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("QuantityFromAnothersImported_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("QuantityFromAnothers_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("QuantityRefined_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("QuantityRemovedFromAccount_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("QuantityTransferredToAnother_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int?>("ReportId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.ToTable("form_24");
                });

            modelBuilder.Entity("Models.Form25", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AlphaActivity_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("BetaGammaActivity_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("CellMass_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("CodeOYAT_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<short>("CorrectionNumber_DB")
                        .HasColumnType("SMALLINT");

                    b.Property<string>("FcpNumber_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("FormNum_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("FuelMass_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int>("NumberInOrder_DB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfFields_DB")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Quantity_DB")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReportId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StoragePlaceCode_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("StoragePlaceName_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.ToTable("form_25");
                });

            modelBuilder.Entity("Models.Form26", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AverageYearConcentration_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("ControlledAreaName_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<short>("CorrectionNumber_DB")
                        .HasColumnType("SMALLINT");

                    b.Property<string>("DistanceToWasteSource_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("FormNum_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int>("NumberInOrder_DB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfFields_DB")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ObservedSourceNumber_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("RadionuclidName_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int?>("ReportId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SupposedWasteSource_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("TestDepth_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.ToTable("form_26");
                });

            modelBuilder.Entity("Models.Form27", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AllowedWasteValue_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<short>("CorrectionNumber_DB")
                        .HasColumnType("SMALLINT");

                    b.Property<string>("FactedWasteValue_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("FormNum_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int>("NumberInOrder_DB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfFields_DB")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ObservedSourceNumber_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("RadionuclidName_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int?>("ReportId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WasteOutbreakPreviousYear_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.ToTable("form_27");
                });

            modelBuilder.Entity("Models.Form28", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AllowedWasteRemovalVolume_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<short>("CorrectionNumber_DB")
                        .HasColumnType("SMALLINT");

                    b.Property<string>("FormNum_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int>("NumberInOrder_DB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfFields_DB")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PoolDistrictName_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("RecieverTypeCode_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("RemovedWasteVolume_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int?>("ReportId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WasteRecieverName_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("WasteSourceName_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.ToTable("form_28");
                });

            modelBuilder.Entity("Models.Form29", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AllowedActivity_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<short>("CorrectionNumber_DB")
                        .HasColumnType("SMALLINT");

                    b.Property<string>("FactedActivity_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("FormNum_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int>("NumberInOrder_DB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfFields_DB")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RadionuclidName_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int?>("ReportId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WasteSourceName_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.ToTable("form_29");
                });

            modelBuilder.Entity("Models.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("GraphNumber_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int?>("ReportId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RowNumber_DB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.ToTable("notes");
                });

            modelBuilder.Entity("Models.Collections.Report", b =>
                {
                    b.HasOne("Models.Collections.Reports", null)
                        .WithMany("Report_Collection")
                        .HasForeignKey("ReportsId");
                });

            modelBuilder.Entity("Models.Collections.Reports", b =>
                {
                    b.HasOne("Models.Collections.DBObservable", null)
                        .WithMany("Reports_Collection")
                        .HasForeignKey("DBObservableId");

                    b.HasOne("Models.Collections.Report", "Master_DB")
                        .WithMany()
                        .HasForeignKey("Master_DBId");

                    b.Navigation("Master_DB");
                });

            modelBuilder.Entity("Models.Form10", b =>
                {
                    b.HasOne("Models.Collections.Report", null)
                        .WithMany("Rows10")
                        .HasForeignKey("ReportId");
                });

            modelBuilder.Entity("Models.Form11", b =>
                {
                    b.HasOne("Models.Collections.Report", null)
                        .WithMany("Rows11")
                        .HasForeignKey("ReportId");
                });

            modelBuilder.Entity("Models.Form12", b =>
                {
                    b.HasOne("Models.Collections.Report", null)
                        .WithMany("Rows12")
                        .HasForeignKey("ReportId");
                });

            modelBuilder.Entity("Models.Form13", b =>
                {
                    b.HasOne("Models.Collections.Report", null)
                        .WithMany("Rows13")
                        .HasForeignKey("ReportId");
                });

            modelBuilder.Entity("Models.Form14", b =>
                {
                    b.HasOne("Models.Collections.Report", null)
                        .WithMany("Rows14")
                        .HasForeignKey("ReportId");
                });

            modelBuilder.Entity("Models.Form15", b =>
                {
                    b.HasOne("Models.Collections.Report", null)
                        .WithMany("Rows15")
                        .HasForeignKey("ReportId");
                });

            modelBuilder.Entity("Models.Form16", b =>
                {
                    b.HasOne("Models.Collections.Report", null)
                        .WithMany("Rows16")
                        .HasForeignKey("ReportId");
                });

            modelBuilder.Entity("Models.Form17", b =>
                {
                    b.HasOne("Models.Collections.Report", null)
                        .WithMany("Rows17")
                        .HasForeignKey("ReportId");
                });

            modelBuilder.Entity("Models.Form18", b =>
                {
                    b.HasOne("Models.Collections.Report", null)
                        .WithMany("Rows18")
                        .HasForeignKey("ReportId");
                });

            modelBuilder.Entity("Models.Form19", b =>
                {
                    b.HasOne("Models.Collections.Report", null)
                        .WithMany("Rows19")
                        .HasForeignKey("ReportId");
                });

            modelBuilder.Entity("Models.Form20", b =>
                {
                    b.HasOne("Models.Collections.Report", null)
                        .WithMany("Rows20")
                        .HasForeignKey("ReportId");
                });

            modelBuilder.Entity("Models.Form21", b =>
                {
                    b.HasOne("Models.Collections.Report", null)
                        .WithMany("Rows21")
                        .HasForeignKey("ReportId");
                });

            modelBuilder.Entity("Models.Form210", b =>
                {
                    b.HasOne("Models.Collections.Report", null)
                        .WithMany("Rows210")
                        .HasForeignKey("ReportId");
                });

            modelBuilder.Entity("Models.Form211", b =>
                {
                    b.HasOne("Models.Collections.Report", null)
                        .WithMany("Rows211")
                        .HasForeignKey("ReportId");
                });

            modelBuilder.Entity("Models.Form212", b =>
                {
                    b.HasOne("Models.Collections.Report", null)
                        .WithMany("Rows212")
                        .HasForeignKey("ReportId");
                });

            modelBuilder.Entity("Models.Form22", b =>
                {
                    b.HasOne("Models.Collections.Report", null)
                        .WithMany("Rows22")
                        .HasForeignKey("ReportId");
                });

            modelBuilder.Entity("Models.Form23", b =>
                {
                    b.HasOne("Models.Collections.Report", null)
                        .WithMany("Rows23")
                        .HasForeignKey("ReportId");
                });

            modelBuilder.Entity("Models.Form24", b =>
                {
                    b.HasOne("Models.Collections.Report", null)
                        .WithMany("Rows24")
                        .HasForeignKey("ReportId");
                });

            modelBuilder.Entity("Models.Form25", b =>
                {
                    b.HasOne("Models.Collections.Report", null)
                        .WithMany("Rows25")
                        .HasForeignKey("ReportId");
                });

            modelBuilder.Entity("Models.Form26", b =>
                {
                    b.HasOne("Models.Collections.Report", null)
                        .WithMany("Rows26")
                        .HasForeignKey("ReportId");
                });

            modelBuilder.Entity("Models.Form27", b =>
                {
                    b.HasOne("Models.Collections.Report", null)
                        .WithMany("Rows27")
                        .HasForeignKey("ReportId");
                });

            modelBuilder.Entity("Models.Form28", b =>
                {
                    b.HasOne("Models.Collections.Report", null)
                        .WithMany("Rows28")
                        .HasForeignKey("ReportId");
                });

            modelBuilder.Entity("Models.Form29", b =>
                {
                    b.HasOne("Models.Collections.Report", null)
                        .WithMany("Rows29")
                        .HasForeignKey("ReportId");
                });

            modelBuilder.Entity("Models.Note", b =>
                {
                    b.HasOne("Models.Collections.Report", null)
                        .WithMany("Notes")
                        .HasForeignKey("ReportId");
                });

            modelBuilder.Entity("Models.Collections.DBObservable", b =>
                {
                    b.Navigation("Reports_Collection");
                });

            modelBuilder.Entity("Models.Collections.Report", b =>
                {
                    b.Navigation("Notes");

                    b.Navigation("Rows10");

                    b.Navigation("Rows11");

                    b.Navigation("Rows12");

                    b.Navigation("Rows13");

                    b.Navigation("Rows14");

                    b.Navigation("Rows15");

                    b.Navigation("Rows16");

                    b.Navigation("Rows17");

                    b.Navigation("Rows18");

                    b.Navigation("Rows19");

                    b.Navigation("Rows20");

                    b.Navigation("Rows21");

                    b.Navigation("Rows210");

                    b.Navigation("Rows211");

                    b.Navigation("Rows212");

                    b.Navigation("Rows22");

                    b.Navigation("Rows23");

                    b.Navigation("Rows24");

                    b.Navigation("Rows25");

                    b.Navigation("Rows26");

                    b.Navigation("Rows27");

                    b.Navigation("Rows28");

                    b.Navigation("Rows29");
                });

            modelBuilder.Entity("Models.Collections.Reports", b =>
                {
                    b.Navigation("Report_Collection");
                });
#pragma warning restore 612, 618
        }
    }
}
